name: utun0
address: '10.0.0.1'
port: 1194
secret: XnV8Ld/BiiWyaXKwBeJSDu7KBrR4+DRCh7rJddzdAIM=
pubkey: /3W5JuHebZQq8WcJTBA5Jjw4j3jpHBExEj+cWjxVGlg=
peers:
  '10.0.0.2':
    sock_addr: '192.68.100.2:1194'
    pub_key: stz+nx0owtXl1A69PI0un04kswigClGwwXN3Rjmtfyw=
  '10.0.0.1':
    sock_addr: '192.68.100.1:1194'
    pub_key: stz+nx0owtXl1A69PI0un04kswigClGwwXN3Rjmtfyw=
